name: Build Documentation and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Dependencies
        run: |
          sudo apt install doxygen
          wget https://cloud.cubert-gmbh.de/index.php/s/m1WfR66TjcGl96z/download
          unzip download
          cd latest_release
          cd Ubuntu\ 20.04/
          sudo apt install ./cuviscommon_3.2.3-1.deb -y
          sudo dpkg -i --force-overwrite ./libcuvis_3.2.3-1.deb
          cd ../..
          pip install -r docs/requirements.txt

      - name: Build
        run: |
          mkdir _build
          cmake -B ./_build .
          cmake --build "_build"
          touch ./_build/doc/sphinx/.nojekyll
          

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./_build/doc/sphinx

