name: Build Documentation and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Dependencies
        run: |
          sudo apt install doxygen
          wget https://cloud.cubert-gmbh.de/index.php/s/qpxkyWkycrmBK9m/download
          unzip download
          cd Cuvis\ 3.3
          cd Cuvis\ 3.3.0\ beta\ 1
          cd Ubuntu\ 20.04/
          sudo apt install ./cuviscommon_3.3.0-1.deb -y
          sudo dpkg -i --force-overwrite ./libcuvis_3.3.0-1.deb
          cd ../../..
          python -m venv venv
          source venv/bin/activate
          pip install -r docs/requirements.txt

      - name: Build Pyil Wrapper
        run: |
          mkdir _build
          cmake -B ./_build -DPython_ROOT_DIR=venv .
          cmake --build "_pyil" --config Release
          cp ./_pyil/_cuvis_pyil.so ./cuvis.pyil/cuvis_il
          cp ./_pyil/_cuvis_il.py ./cuvis.pyil/cuvis_il
          pip install cuvis.pyil
          pip install cuvis.python
          
      - name: Build Documentation
        run: |
          cmake --build "_build"
          touch ./_build/doc/sphinx/.nojekyll  
          

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./_build/doc/sphinx

